# Generated by Django 3.1.5 on 2021-05-18 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered_on',
            field=models.DateField(default=datetime.date(2021, 5, 18)),
        ),
    ]
