# Generated by Django 3.1.5 on 2021-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='food',
        ),
        migrations.AddField(
            model_name='hotel',
            name='foodCate',
            field=models.ManyToManyField(blank=True, to='hotels.Category'),
        ),
    ]
