# Generated by Django 3.1.5 on 2021-05-14 10:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_from',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
